#PARA PRUEBAS DE DESPLIEGE CON IDENTIDAD ADMINISTRADA SYSTEM ASSIGNED
#spring.application.name=EciBombit
#server.port=8080
#spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://key-vault-bombit.vault.azure.net/
#spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true
#spring.data.mongodb.uri=${mongo-uri}
#spring.data.mongodb.database=${mongo-db}

PARA PRUEBAS LOCALES CON SERVICE PRINCIPAL
spring.application.name=EciBombit
server.port=8080
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://key-vault-bombit.vault.azure.net/
spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.credential.client-secret=${AZURE_CLIENT_SECRET}
spring.cloud.azure.credential.tenant-id=${AZURE_TENANT_ID}
spring.data.mongodb.uri=${mongo-uri}
spring.data.mongodb.database=${mongo-db}